# Generated by Django 5.1.6 on 2025-02-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('GAIN', 'Gain'), ('LOSS', 'Loss')], default='gain', max_length=100)),
                ('size', models.DecimalField(decimal_places=2, max_digits=100)),
                ('sphere', models.CharField(choices=[('', ''), ('HOUSING', 'Housing'), ('FOOD', 'Food'), ('TRANSPORT', 'Transport'), ('ENJOYMENT', 'Enjoyment'), ('DEPOSIT', 'Deposit')], default='', max_length=100)),
            ],
            options={
                'ordering': ['added'],
            },
        ),
    ]
