# Generated by Django 5.1.6 on 2025-02-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='type',
            field=models.CharField(choices=[('GAIN', 'Gain'), ('LOSS', 'Loss')], default='Gain', max_length=100),
        ),
    ]
