# Generated by Django 5.1.6 on 2025-02-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_records_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='currency',
            field=models.CharField(choices=[('USD', 'usd'), ('EUR', 'eur'), ('RUB', 'rub')], default='rub', max_length=10),
        ),
    ]
