# Generated by Django 5.1.6 on 2025-03-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_records_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='currency',
            field=models.CharField(choices=[('USD', 'usd'), ('EUR', 'eur'), ('RUB', 'rub')], default='RUB', max_length=10),
        ),
        migrations.AlterField(
            model_name='records',
            name='type',
            field=models.CharField(choices=[('GAIN', 'Gain'), ('LOSS', 'Loss')], default='GAIN', max_length=100),
        ),
    ]
